### ISSUE TITLE
Totally Not Working on TECNO Camon CX Air

### ISSUE THREAD

**Issue by mikesew1320** [therealahrion/AM3D-Zirene-Sound#5]
I downloaded the module from github and installed via magisk manager then I rebooted my phone and opened the app from the drawer it says me please wait for first time but next time it closed automatically when I am trying to open it!

Please fix this issue if you can.

If you want to contact me use my E-mail -------  mikesew1320@gmail.com

My phone is TECNI CX AIR MT6737M 2GBRAM 16GBROM ANDROID 7.0 AOSP

**Comment by Zackptg5** [comment]
You'll want to bring this up on the support thread: https://forum.xda-developers.com/android/apps-games/mod-zirene-sound-am3d-t3396698

There's troubleshooting instructions in the OP but this mod has been discontinued due to the app being EOL and pretty much doesn't work on newer roms
